### ISSUE TITLE
Make set username conditional on Config setting

### ISSUE THREAD

**Issue by yogiben** [yogiben/meteor-starter#20]
Set username screen should only apply when `username: true` in Config.

```
@Config =
    name: 'My App'
    title: 'Make Meteor Apps. Fast.'
    subtitle: 'Create beautiful  Meteor apps really fast'
    logo: ->
        '<b>' + @name + '</b>'
    footer: ->
        @name + ' - Copyright ' + new Date().getFullYear()
    emails:
        from: 'noreply@' + Meteor.absoluteUrl()
    blog: 'http://meteorfactory.io'
    about: 'http://meteorfactory.io'
    username: false
    homeRoute: '/'
    dashboardRoute: '/dashboard'
    socialMedia:
        facebook:
            url: 'http://facebook.com/benjaminpeterjones'
            icon: 'facebook'
        twitter:
            url: 'http://twitter.com/BenPeterJones'
            icon: 'twitter'
        github:
            url: 'http://github.com/yogiben'
            icon: 'github'
    publicRoutes: ['home']
```
